Tank Controller Lib: test/Blink.cpp File Reference
Blink.cpp File Reference
#include <Arduino.h>
#include <ArduinoUnitTests.h>
#include <ci/ObservableDataStream.h>
#include <iostream>
#include "TankControllerLib.h"
Classes
class BitCollector
Macros
#define LED_PIN 13
Functions
unittest (loop)
Variables
GodmodeState * state = GODMODE()
const int logSize = 10
struct {
long time
bool value
} pinLog [logSize]
int logIndex = 0
bool overflowFlag = false
Macro Definition Documentation
LED_PIN
#define LED_PIN 13
Definition at line 9 of file Blink.cpp.
Function Documentation
unittest()
unittest (loop)
Definition at line 40 of file Blink.cpp.
                {
   BitCollector led;
   logIndex = 0;
   TankControllerLib* tank = TankControllerLib::instance();
   state->resetClock();
   state->digitalPin[LED_BUILTIN].addObserver("led", &led);
   tank->setup();
   tank->loop();
   delay(500);
   tank->loop();
   delay(500);
   tank->loop();
   delay(500);
   tank->loop();
   delay(500);
   state->digitalPin[LED_BUILTIN].removeObserver("led");
   assertFalse(overflowFlag);
   assertEqual(4, logIndex);
   assertEqual(0, pinLog[0].time);
   assertEqual(HIGH, pinLog[0].value);
   assertEqual(500000, pinLog[1].time);
   assertEqual(LOW, pinLog[1].value);
   assertEqual(1000000, pinLog[2].time);
   assertEqual(HIGH, pinLog[2].value);
   assertEqual(1500000, pinLog[3].time);
   assertEqual(LOW, pinLog[3].value);
 }
References TankControllerLib::instance(), logIndex, TankControllerLib::loop(), overflowFlag, pinLog, TankControllerLib::setup(), state, time, and value.
Variable Documentation
logIndex
int logIndex = 0
Definition at line 17 of file Blink.cpp.
Referenced by BitCollector::onBit(), and unittest().
logSize
const int logSize = 10
Definition at line 12 of file Blink.cpp.
Referenced by BitCollector::onBit().
overflowFlag
bool overflowFlag = false
Definition at line 18 of file Blink.cpp.
Referenced by BitCollector::onBit(), and unittest().
struct { ... } pinLog[logSize]
Referenced by BitCollector::onBit(), and unittest().
state
GodmodeState* state = GODMODE()
Definition at line 11 of file Blink.cpp.
Referenced by UIState::changeState(), BitCollector::onBit(), and unittest().
time
long time
Definition at line 14 of file Blink.cpp.
Referenced by unittest().
value
bool value
Definition at line 15 of file Blink.cpp.
Referenced by Serial_TC::print_two_digits(), and unittest().