Tank Controller Lib: SetTempSetPoint Class Reference
SetTempSetPoint Class Reference
#include <SetTempSetPoint.h>
Public Member Functions
const char * prompt ()
int getExpectedDigits ()
void setValue (double value)
Public Member Functions inherited from NumCollectorState
NumCollectorState ()
void handleKey (char key)
Public Member Functions inherited from UIState
UIState ()
virtual ~UIState ()
Additional Inherited Members
Protected Member Functions inherited from NumCollectorState
void handleDigit (int digit)
void backSpace ()
void printValue ()
bool collectedEnoughDigits ()
Protected Member Functions inherited from UIState
void changeState (UIState *state)
Protected Attributes inherited from NumCollectorState
double value = 0.0
int numDigits = 0
int factor = 10
bool hasDecimal = false
Detailed Description
SetTempSetPoint.h
Set the target Temperature
Definition at line 9 of file SetTempSetPoint.h.
Member Function Documentation
getExpectedDigits()
int SetTempSetPoint::getExpectedDigits () inline virtual
Implements NumCollectorState.
Definition at line 14 of file SetTempSetPoint.h.
{
     return 4;
   };
prompt()
const char* SetTempSetPoint::prompt () inline virtual
Implements UIState.
Definition at line 11 of file SetTempSetPoint.h.
{
     return "Set Temperature ";
   };
setValue()
void SetTempSetPoint::setValue (double value) virtual
SetTemperatureSetPoint.cpp
Implements NumCollectorState.
Definition at line 10 of file SetTempSetPoint.cpp.
{
   EEPROM_TC::instance()->setTemp(value);
   char output[16];
   sprintf(output, "New Temp=%.2f", value);
   LiquidCrystal_TC::instance()->writeLine(output, 1);
   delay(1000);  // 1second
   this->changeState((UIState *)new MainMenu);
 }
References UIState::changeState(), EEPROM_TC::instance(), LiquidCrystal_TC::instance(), EEPROM_TC::setTemp(), NumCollectorState::value, and LiquidCrystal_TC::writeLine().
The documentation for this class was generated from the following files:
src/UIState/SetTempSetPoint.h
src/UIState/SetTempSetPoint.cpp