Tank Controller Lib: TankController.TankController Class Reference
TankController.TankController Class Reference
Public Member Functions
def __init__ (self, parent, title)
def InitUI (self)
def KeypadEvent (self, event)
def Keyboard (self, event)
Public Attributes
lqd
Static Public Attributes
list labels
Detailed Description
Definition at line 11 of file TankController.py.
Constructor & Destructor Documentation
__init__()
def TankController.TankController.__init__ (self, parent, title)
Definition at line 16 of file TankController.py.
   def __init__(self, parent, title):
     super(TankController, self).__init__(parent, title = title, size = (220,300))
     self.InitUI()
     self.Centre()
     self.Show()
References TankController.TankController.InitUI().
Member Function Documentation
InitUI()
def TankController.TankController.InitUI (self)
Definition at line 22 of file TankController.py.
   def InitUI(self):
     panel = wx.Panel(self)
     panel.Bind(wx.EVT_CHAR, self.Keyboard)
     mainSizer = wx.BoxSizer(wx.VERTICAL)
     version = wx.StaticText(panel, label="Version " + libTC.version())
     mainSizer.Add(version,1)
     lqdSizer = wx.StaticBoxSizer(wx.VERTICAL, panel)
     self.lqd = wx.StaticText(panel, label = libTC.lcd(0) + '\n' + libTC.lcd(1))
     font = wx.Font(20, wx.FONTFAMILY_TELETYPE, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL)
     self.lqd.SetFont(font)
     lqdSizer.Add(self.lqd, 1)
     mainSizer.Add(lqdSizer,1)
     keypadSizer = wx.StaticBoxSizer(wx.VERTICAL, panel)
     keypadGrid = wx.GridSizer(4, 4, 5, 5)
     for each in self.labels:
       button = wx.Button(panel, label = each)
       button.Bind(wx.EVT_LEFT_UP, self.KeypadEvent)
       keypadGrid.Add(button, 0, wx.EXPAND)
     keypadSizer.Add(keypadGrid, 1)
     mainSizer.Add(keypadSizer, 2)
     tankSizer = wx.StaticBoxSizer(wx.VERTICAL, panel, label="Tank Simulation")
     tank = wx.StaticText(panel, label = "TANK")
     tankSizer.Add(tank, 1)
     mainSizer.Add(tankSizer, 3)
     panel.SetSizer(mainSizer)
References TankController.TankController.Keyboard().
Referenced by TankController.TankController.__init__().
Keyboard()
def TankController.TankController.Keyboard (self, event)
Definition at line 62 of file TankController.py.
   def Keyboard(self, event):
     key = chr(event.GetUnicodeKey()).upper()
     print("Keyboard", key)
Referenced by TankController.TankController.InitUI().
KeypadEvent()
def TankController.TankController.KeypadEvent (self, event)
Definition at line 55 of file TankController.py.
   def KeypadEvent(self, event):
     key = event.GetEventObject().GetLabel()
     libTC.key(key)
     libTC.loop()
     self.lqd.SetLabelText(libTC.lcd(0) + '\n' + libTC.lcd(1))
     print("Keypad", key)
References TankController.TankController.lqd.
Member Data Documentation
labels
list TankController.TankController.labels static
Initial value:
=  ['1', '2', '3', 'A',
            '4', '5', '6', 'B',
            '7', '8', '9', 'C',
            '*', '0', '#', 'D']
Definition at line 12 of file TankController.py.
lqd
TankController.TankController.lqd
Definition at line 32 of file TankController.py.
Referenced by TankController.TankController.KeypadEvent().
The documentation for this class was generated from the following file:
GUI/TankController.py