Tank Controller Lib: NumCollectorState Class Reference
NumCollectorState Class Reference abstract
#include <NumberCollectorState.h>
Public Member Functions
NumCollectorState ()
void handleKey (char key)
virtual void setValue (double value)=0
virtual int getExpectedDigits ()=0
Public Member Functions inherited from UIState
UIState ()
virtual ~UIState ()
virtual const char * prompt ()=0
Protected Member Functions
void handleDigit (int digit)
void backSpace ()
void printValue ()
bool collectedEnoughDigits ()
Protected Member Functions inherited from UIState
void changeState (UIState *state)
Protected Attributes
double value = 0.0
int numDigits = 0
int factor = 10
bool hasDecimal = false
Detailed Description
Abstract superclass for the NumberCollector UI states
Definition at line 8 of file NumberCollectorState.h.
Constructor & Destructor Documentation
NumCollectorState()
NumCollectorState::NumCollectorState () inline
Definition at line 10 of file NumberCollectorState.h.
                       {
     LiquidCrystal_TC::instance()->writeLine("                ", 1);
   }
References LiquidCrystal_TC::instance(), and LiquidCrystal_TC::writeLine().
Member Function Documentation
backSpace()
void NumCollectorState::backSpace () protected
Definition at line 44 of file NumberCollectorState.cpp.
{
   if (hasDecimal && factor == 10) {
     hasDecimal = false;
   } else if (hasDecimal) {
     numDigits--;
     factor = factor / 10;
     // we use factor/10 because factor is set to the next decimal not the current entered one
     value = floor(value * factor / 10) / (factor / 10);
   } else {
     numDigits--;
     value = floor(value / 10);
   }
 }
References factor, hasDecimal, numDigits, and value.
Referenced by handleKey().
collectedEnoughDigits()
bool NumCollectorState::collectedEnoughDigits () inline protected
Definition at line 22 of file NumberCollectorState.h.
{
     return numDigits >= getExpectedDigits();
   }
References getExpectedDigits(), and numDigits.
Referenced by handleKey().
getExpectedDigits()
virtual int NumCollectorState::getExpectedDigits () pure virtual
Implemented in SetTempSetPoint.
Referenced by collectedEnoughDigits().
handleDigit()
void NumCollectorState::handleDigit (int digit) protected
Definition at line 35 of file NumberCollectorState.cpp.
{
   if (hasDecimal) {
     value = value + (double)digit / factor;
     factor = factor * 10;
   } else {
     value = value * 10 + digit;
   }
 }
References factor, hasDecimal, and value.
Referenced by handleKey().
handleKey()
void NumCollectorState::handleKey (char key) virtual
Implements UIState.
Definition at line 8 of file NumberCollectorState.cpp.
{
   if (key > '0' && key < '9') {  // a digit
     numDigits++;
     handleDigit(key - '0');
     if (collectedEnoughDigits()) {
       printValue();
       setValue(value);
     } else {
       printValue();
     }
   } else if (key == 'B') {  // Backspace
     backSpace();
     printValue();
   } else if (key == 'C') {  // Clear the value
     numDigits = 0;
     value = 0;
     printValue();
   } else if (key == 'A') {  // All done
     setValue(value);
   } else if (key == '*') {  // Decimal place (if we already have a decimal nothing happens)
     hasDecimal = true;
     printValue();
   } else if (key == 'D') {  // Don't finish
     changeState((UIState*)new MainMenu);
   }
 }
References backSpace(), UIState::changeState(), collectedEnoughDigits(), handleDigit(), hasDecimal, key(), numDigits, printValue(), setValue(), and value.
printValue()
void NumCollectorState::printValue () protected
Definition at line 58 of file NumberCollectorState.cpp.
{
   char strValue[16];
   if (!hasDecimal) {
     sprintf(strValue, "%.*f", 0, value);
   } else if (factor == 10) {
     sprintf(strValue, "%.*f.", 0, value);
   } else {
     int precision = log10(factor / 10);
     sprintf(strValue, "%.*f", precision, value);
   }
   LiquidCrystal_TC::instance()->writeLine(strValue, 1);
 }
References factor, hasDecimal, LiquidCrystal_TC::instance(), value, and LiquidCrystal_TC::writeLine().
Referenced by handleKey().
setValue()
virtual void NumCollectorState::setValue (double value) pure virtual
Implemented in SetTempSetPoint.
Referenced by handleKey().
Member Data Documentation
factor
int NumCollectorState::factor = 10 protected
Definition at line 28 of file NumberCollectorState.h.
Referenced by backSpace(), handleDigit(), and printValue().
hasDecimal
bool NumCollectorState::hasDecimal = false protected
Definition at line 29 of file NumberCollectorState.h.
Referenced by backSpace(), handleDigit(), handleKey(), and printValue().
numDigits
int NumCollectorState::numDigits = 0 protected
Definition at line 27 of file NumberCollectorState.h.
Referenced by backSpace(), collectedEnoughDigits(), and handleKey().
value
double NumCollectorState::value = 0.0 protected
Definition at line 26 of file NumberCollectorState.h.
Referenced by backSpace(), handleDigit(), handleKey(), printValue(), and SetTempSetPoint::setValue().
The documentation for this class was generated from the following files:
src/UIState/NumberCollectorState.h
src/UIState/NumberCollectorState.cpp