Tank Controller Lib: Ethernet_TC Class Reference
Ethernet_TC Class Reference
#include <Ethernet_TC.h>
Public Member Functions
IPAddress getIP ()
int getNumAttemptedDHCPReleases ()
void renewDHCPLease ()
bool gotDHCPLease ()
Static Public Member Functions
static Ethernet_TC * getInstance ()
Protected Member Functions
Ethernet_TC ()
Private Attributes
byte mac [6] = {0x90, 0xA2, 0xDA, 0x00, 0x00, 0x00}
IPAddress defaultIP = IPAddress(192, 168, 1, 2)
IPAddress time_serverIP
IPAddress IP
unsigned long previous_lease = 0
const unsigned long LEASE_INTERVAL = 345600000
int numAttemptedDHCPReleases = 0
Static Private Attributes
static Ethernet_TC * _instance = nullptr
Detailed Description
Based off Arduino's Ethernet library Implements a wrapper for the Ethernet Class
Definition at line 10 of file Ethernet_TC.h.
Constructor & Destructor Documentation
Ethernet_TC()
Ethernet_TC::Ethernet_TC () protected
Definition at line 6 of file Ethernet_TC.cpp.
{
   if (Ethernet.begin(mac) == 0) {
     Serial.println(F("Failed to configure Ethernet using DHCP"));
     Ethernet.begin(mac, defaultIP);
     IP = defaultIP;
   }
 }
References defaultIP, IP, and mac.
Referenced by getInstance().
Member Function Documentation
getInstance()
Ethernet_TC * Ethernet_TC::getInstance () static
Definition at line 14 of file Ethernet_TC.cpp.
{
   if (_instance == nullptr) {
     _instance = new Ethernet_TC;
   }
   return _instance;
 }
References _instance, and Ethernet_TC().
Referenced by unittest().
getIP()
IPAddress Ethernet_TC::getIP () inline
Definition at line 13 of file Ethernet_TC.h.
                     {
     return IP;
   };
References IP.
Referenced by unittest().
getNumAttemptedDHCPReleases()
int Ethernet_TC::getNumAttemptedDHCPReleases () inline
Definition at line 16 of file Ethernet_TC.h.
{
     return numAttemptedDHCPReleases;
   };
References numAttemptedDHCPReleases.
Referenced by unittest().
gotDHCPLease()
bool Ethernet_TC::gotDHCPLease () inline
Definition at line 20 of file Ethernet_TC.h.
                       {
     return IP != defaultIP;
   };
References defaultIP, and IP.
renewDHCPLease()
void Ethernet_TC::renewDHCPLease ()
Definition at line 21 of file Ethernet_TC.cpp.
{
   unsigned long current_millis = millis();
   if ((current_millis - previous_lease) >= LEASE_INTERVAL || current_millis < previous_lease) {
     Ethernet.maintain();
     previous_lease = current_millis;
   }
   numAttemptedDHCPReleases++;
 }
References LEASE_INTERVAL, numAttemptedDHCPReleases, and previous_lease.
Referenced by unittest().
Member Data Documentation
_instance
Ethernet_TC * Ethernet_TC::_instance = nullptr static private
Definition at line 28 of file Ethernet_TC.h.
Referenced by getInstance().
defaultIP
IPAddress Ethernet_TC::defaultIP = IPAddress(192, 168, 1, 2) private
Definition at line 30 of file Ethernet_TC.h.
Referenced by Ethernet_TC(), and gotDHCPLease().
IP
IPAddress Ethernet_TC::IP private
Definition at line 32 of file Ethernet_TC.h.
Referenced by Ethernet_TC(), getIP(), and gotDHCPLease().
LEASE_INTERVAL
const unsigned long Ethernet_TC::LEASE_INTERVAL = 345600000 private
Definition at line 34 of file Ethernet_TC.h.
Referenced by renewDHCPLease().
mac
byte Ethernet_TC::mac[6] = {0x90, 0xA2, 0xDA, 0x00, 0x00, 0x00} private
Definition at line 29 of file Ethernet_TC.h.
Referenced by Ethernet_TC().
numAttemptedDHCPReleases
int Ethernet_TC::numAttemptedDHCPReleases = 0 private
Definition at line 37 of file Ethernet_TC.h.
Referenced by getNumAttemptedDHCPReleases(), and renewDHCPLease().
previous_lease
unsigned long Ethernet_TC::previous_lease = 0 private
Definition at line 33 of file Ethernet_TC.h.
Referenced by renewDHCPLease().
time_serverIP
IPAddress Ethernet_TC::time_serverIP private
Definition at line 31 of file Ethernet_TC.h.
The documentation for this class was generated from the following files:
src/Devices/Ethernet_TC.h
src/Devices/Ethernet_TC.cpp