Tank Controller Lib: TankControllerLib Class Reference
TankControllerLib Class Reference
#include <TankControllerLib.h>
Public Member Functions
void setup ()
void loop ()
const char * version ()
Static Public Member Functions
static TankControllerLib * instance ()
Private Member Functions
TankControllerLib ()
~TankControllerLib ()
void blink ()
void changeState (UIState *newState)
Private Attributes
UIState * state
LiquidCrystal_TC * lcd
Serial_TC * log
Static Private Attributes
static TankControllerLib * _instance = nullptr
Friends
class UIState
Detailed Description
Definition at line 13 of file TankControllerLib.h.
Constructor & Destructor Documentation
TankControllerLib()
TankControllerLib::TankControllerLib () private
Constructor
Definition at line 33 of file TankControllerLib.cpp.
{
   assert(!_instance);
   state = new MainMenu;
   lcd = LiquidCrystal_TC::instance();
   log = Serial_TC::instance();
   log->print(F("TankControllerLib::TankControllerLib() - version "), TANK_CONTROLLER_VERSION);
 }
References _instance, assert, LiquidCrystal_TC::instance(), Serial_TC::instance(), lcd, log, Serial_TC::print(), state, and TANK_CONTROLLER_VERSION.
Referenced by instance().
~TankControllerLib()
TankControllerLib::~TankControllerLib () private
Destructor
Definition at line 44 of file TankControllerLib.cpp.
{
   changeState(nullptr);
   assert(this == _instance);
   _instance = nullptr;
 }
References _instance, assert, and changeState().
Member Function Documentation
blink()
void TankControllerLib::blink () private
Blink the on-board LED to let us know that loop() is being called
Definition at line 54 of file TankControllerLib.cpp.
{
   if (millis() / 500 % 2) {
     digitalWrite(LED_BUILTIN, LOW);  // turn the LED off by making the voltage LOW
   } else {
     digitalWrite(LED_BUILTIN, HIGH);  // turn the LED on (HIGH is the voltage level)
   }
 }
Referenced by loop().
changeState()
void TankControllerLib::changeState (UIState * newState) private
Private member function called by UIState subclasses
Definition at line 65 of file TankControllerLib.cpp.
{
   if (state) {
     delete state;
   }
   state = newState;
 }
References state.
Referenced by UIState::changeState(), setup(), and ~TankControllerLib().
instance()
TankControllerLib * TankControllerLib::instance () static
static function to return singleton
Definition at line 22 of file TankControllerLib.cpp.
{
   if (!_instance) {
     _instance = new TankControllerLib;
   }
   return _instance;
 }
References _instance, and TankControllerLib().
Referenced by UIState::changeState(), loop(), setup(), unittest(), and version().
loop()
void TankControllerLib::loop ()
This is one of two public instance functions. It is called repeatedly while the board is on.
Definition at line 76 of file TankControllerLib.cpp.
{
   blink();  //  blink the on-board LED to show that we are running
   char key = Keypad_TC::instance()->getKey();
   if (key != NO_KEY) {
     log->print(F("Keypad input: "), key);
     state->handleKey(key);
     // print the current prompt on the first line of the display
     LiquidCrystal_TC::instance()->writeLine(state->prompt(), 0);
   }
 }
References blink(), Keypad_TC::getKey(), UIState::handleKey(), Keypad_TC::instance(), LiquidCrystal_TC::instance(), key(), log, Serial_TC::print(), UIState::prompt(), state, and LiquidCrystal_TC::writeLine().
Referenced by loop(), and unittest().
setup()
void TankControllerLib::setup ()
This is one of two public instance functions. Here we do any one-time startup initialization.
Definition at line 91 of file TankControllerLib.cpp.
{
   log->print(F("TankControllerLib::setup()"));
   changeState((UIState*)new MainMenu);
   pinMode(LED_BUILTIN, OUTPUT);
 }
References changeState(), log, and Serial_TC::print().
Referenced by setup(), and unittest().
version()
const char * TankControllerLib::version ()
What is the current version?
Definition at line 100 of file TankControllerLib.cpp.
{
   log->print(F("TankControllerLib::version() = "), TANK_CONTROLLER_VERSION);
   return TANK_CONTROLLER_VERSION;
 }
References log, Serial_TC::print(), and TANK_CONTROLLER_VERSION.
Referenced by version().
Friends And Related Function Documentation
UIState
friend class UIState friend
Definition at line 39 of file TankControllerLib.h.
Member Data Documentation
_instance
TankControllerLib * TankControllerLib::_instance = nullptr static private
static variable to hold singleton
Definition at line 25 of file TankControllerLib.h.
Referenced by instance(), TankControllerLib(), and ~TankControllerLib().
lcd
LiquidCrystal_TC* TankControllerLib::lcd private
Definition at line 29 of file TankControllerLib.h.
Referenced by TankControllerLib().
log
Serial_TC* TankControllerLib::log private
Definition at line 30 of file TankControllerLib.h.
Referenced by loop(), setup(), TankControllerLib(), and version().
state
UIState* TankControllerLib::state private
Definition at line 28 of file TankControllerLib.h.
Referenced by changeState(), loop(), and TankControllerLib().
The documentation for this class was generated from the following files:
src/TankControllerLib.h
src/TankControllerLib.cpp