Tank Controller Lib: EEPROM_TC Class Reference
EEPROM_TC Class Reference
#include <EEPROM_TC.h>
Public Member Functions
double getPH ()
double getTemp ()
double getTankID ()
double getCorrectedTemp ()
double getKP ()
double getKI ()
double getKD ()
double getMac ()
double getHeat ()
double getAmplitude ()
double getFrequency ()
double getGranularity ()
double getMaxDataAge ()
double getPHSeriesSize ()
double getPHSeriesPointer ()
double getTempSeriesSize ()
double getTempSeriesPointer ()
double getPHInterval ()
double getPHDelay ()
double getTempInterval ()
double getTempDelay ()
void setPH (double value)
void setTemp (double value)
void setTankID (double value)
void setCorrectedTemp (double value)
void setKP (double value)
void setKI (double value)
void setKD (double value)
void setMac (double value)
void setHeat (double value)
void setAmplitude (double value)
void setFrequency (double value)
void setGranularity (double value)
void setMaxDataAge (double value)
void setPHSeriesSize (double value)
void setPHSeriesPointer (double value)
void setTempSeriesSize (double value)
void setTempSeriesPointer (double value)
void setPHInterval (double value)
void setPHDelay (double value)
void setTempInterval (double value)
void setTempDelay (double value)
double eepromReadDouble (int address)
void eepromWriteDouble (int address, double value)
Static Public Member Functions
static EEPROM_TC * instance ()
Private Member Functions
EEPROM_TC ()
Private Attributes
const int PH_ADDRESS = 0
const int TEMP_ADDRESS = 4
const int TANK_ID_ADDRESS = 8
const int TEMP_CORR_ADDRESS = 12
const int KP_ADDRESS = 20
const int KI_ADDRESS = 28
const int KD_ADDRESS = 36
const int MAC_ADDRESS = 44
const int HEAT_ADDRESS = 52
const int AMPLITUDE_ADDRESS = 56
const int FREQUENCY_ADDRESS = 60
const int GRANULARITY_ADDRESS = 64
const int MAX_DATA_AGE_ADDRESS = 68
const int PH_SERIES_SIZE_ADDRESS = 72
const int PH_SERIES_POINTER_ADDRESS = 76
const int TEMP_SERIES_SIZE_ADDRESS = 80
const int TEMP_SERIES_POINTER_ADDRESS = 84
const int PH_INTERVAL_ADDRESS = 88
const int PH_DELAY_ADDRESS = 92
const int TEMP_INTERVAL_ADDRESS = 96
const int TEMP_DELAY_ADDRESS = 100
Static Private Attributes
static EEPROM_TC * _instance = nullptr
Detailed Description
Definition at line 6 of file EEPROM_TC.h.
Constructor & Destructor Documentation
EEPROM_TC()
EEPROM_TC::EEPROM_TC () private
Definition at line 18 of file EEPROM_TC.cpp.
                      {
 }
Referenced by instance().
Member Function Documentation
eepromReadDouble()
double EEPROM_TC::eepromReadDouble (int address)
Definition at line 21 of file EEPROM_TC.cpp.
{
   double value = 0.0;
   byte* p = (byte*)(void*)&value;
   for (int i = 0; i < sizeof(value); i++) {
     *p++ = EEPROM.read(address++);
   }
   return value;
 }
References value.
Referenced by getAmplitude(), getCorrectedTemp(), getFrequency(), getGranularity(), getHeat(), getKD(), getKI(), getKP(), getMac(), getMaxDataAge(), getPH(), getPHDelay(), getPHInterval(), getPHSeriesPointer(), getPHSeriesSize(), getTankID(), getTemp(), getTempDelay(), getTempInterval(), getTempSeriesPointer(), and getTempSeriesSize().
eepromWriteDouble()
void EEPROM_TC::eepromWriteDouble (int address, double value)
Definition at line 30 of file EEPROM_TC.cpp.
{
   byte* p = (byte*)(void*)&value;
   for (int i = 0; i < sizeof(value); i++) {
     EEPROM.update(address++, *p++);
   }
 }
References value.
Referenced by setAmplitude(), setCorrectedTemp(), setFrequency(), setGranularity(), setHeat(), setKD(), setKI(), setKP(), setMac(), setMaxDataAge(), setPH(), setPHDelay(), setPHInterval(), setPHSeriesPointer(), setPHSeriesSize(), setTankID(), setTemp(), setTempDelay(), setTempInterval(), setTempSeriesPointer(), and setTempSeriesSize().
getAmplitude()
double EEPROM_TC::getAmplitude ()
Definition at line 65 of file EEPROM_TC.cpp.
{
   return eepromReadDouble(AMPLITUDE_ADDRESS);
 }
References AMPLITUDE_ADDRESS, and eepromReadDouble().
Referenced by unittest().
getCorrectedTemp()
double EEPROM_TC::getCorrectedTemp ()
Definition at line 47 of file EEPROM_TC.cpp.
{
   return eepromReadDouble(TEMP_CORR_ADDRESS);
 }
References eepromReadDouble(), and TEMP_CORR_ADDRESS.
Referenced by unittest().
getFrequency()
double EEPROM_TC::getFrequency ()
Definition at line 68 of file EEPROM_TC.cpp.
{
   return eepromReadDouble(FREQUENCY_ADDRESS);
 }
References eepromReadDouble(), and FREQUENCY_ADDRESS.
Referenced by unittest().
getGranularity()
double EEPROM_TC::getGranularity ()
Definition at line 71 of file EEPROM_TC.cpp.
{
   return eepromReadDouble(GRANULARITY_ADDRESS);
 }
References eepromReadDouble(), and GRANULARITY_ADDRESS.
Referenced by unittest().
getHeat()
double EEPROM_TC::getHeat ()
Definition at line 62 of file EEPROM_TC.cpp.
{
   return eepromReadDouble(HEAT_ADDRESS);
 }
References eepromReadDouble(), and HEAT_ADDRESS.
Referenced by unittest().
getKD()
double EEPROM_TC::getKD ()
Definition at line 56 of file EEPROM_TC.cpp.
{
   return eepromReadDouble(KD_ADDRESS);
 }
References eepromReadDouble(), and KD_ADDRESS.
Referenced by unittest().
getKI()
double EEPROM_TC::getKI ()
Definition at line 53 of file EEPROM_TC.cpp.
{
   return eepromReadDouble(KI_ADDRESS);
 }
References eepromReadDouble(), and KI_ADDRESS.
Referenced by unittest().
getKP()
double EEPROM_TC::getKP ()
Definition at line 50 of file EEPROM_TC.cpp.
{
   return eepromReadDouble(KP_ADDRESS);
 }
References eepromReadDouble(), and KP_ADDRESS.
Referenced by unittest().
getMac()
double EEPROM_TC::getMac ()
Definition at line 59 of file EEPROM_TC.cpp.
                          {  // See issue #57 about this function
   return eepromReadDouble(MAC_ADDRESS);
 }
References eepromReadDouble(), and MAC_ADDRESS.
Referenced by unittest().
getMaxDataAge()
double EEPROM_TC::getMaxDataAge ()
Definition at line 74 of file EEPROM_TC.cpp.
{
   return eepromReadDouble(MAX_DATA_AGE_ADDRESS);
 }
References eepromReadDouble(), and MAX_DATA_AGE_ADDRESS.
Referenced by unittest().
getPH()
double EEPROM_TC::getPH ()
Definition at line 38 of file EEPROM_TC.cpp.
{
   return eepromReadDouble(PH_ADDRESS);
 }
References eepromReadDouble(), and PH_ADDRESS.
Referenced by unittest().
getPHDelay()
double EEPROM_TC::getPHDelay ()
Definition at line 92 of file EEPROM_TC.cpp.
{
   return eepromReadDouble(PH_DELAY_ADDRESS);
 }
References eepromReadDouble(), and PH_DELAY_ADDRESS.
Referenced by unittest().
getPHInterval()
double EEPROM_TC::getPHInterval ()
Definition at line 89 of file EEPROM_TC.cpp.
{
   return eepromReadDouble(PH_INTERVAL_ADDRESS);
 }
References eepromReadDouble(), and PH_INTERVAL_ADDRESS.
Referenced by unittest().
getPHSeriesPointer()
double EEPROM_TC::getPHSeriesPointer ()
Definition at line 80 of file EEPROM_TC.cpp.
{
   return eepromReadDouble(PH_SERIES_POINTER_ADDRESS);
 }
References eepromReadDouble(), and PH_SERIES_POINTER_ADDRESS.
Referenced by unittest().
getPHSeriesSize()
double EEPROM_TC::getPHSeriesSize ()
Definition at line 77 of file EEPROM_TC.cpp.
{
   return eepromReadDouble(PH_SERIES_SIZE_ADDRESS);
 }
References eepromReadDouble(), and PH_SERIES_SIZE_ADDRESS.
Referenced by unittest().
getTankID()
double EEPROM_TC::getTankID ()
Definition at line 44 of file EEPROM_TC.cpp.
{
   return eepromReadDouble(TANK_ID_ADDRESS);
 }
References eepromReadDouble(), and TANK_ID_ADDRESS.
Referenced by unittest().
getTemp()
double EEPROM_TC::getTemp ()
Definition at line 41 of file EEPROM_TC.cpp.
{
   return eepromReadDouble(TEMP_ADDRESS);
 }
References eepromReadDouble(), and TEMP_ADDRESS.
Referenced by unittest().
getTempDelay()
double EEPROM_TC::getTempDelay ()
Definition at line 98 of file EEPROM_TC.cpp.
{
   return eepromReadDouble(TEMP_DELAY_ADDRESS);
 }
References eepromReadDouble(), and TEMP_DELAY_ADDRESS.
Referenced by unittest().
getTempInterval()
double EEPROM_TC::getTempInterval ()
Definition at line 95 of file EEPROM_TC.cpp.
{
   return eepromReadDouble(TEMP_INTERVAL_ADDRESS);
 }
References eepromReadDouble(), and TEMP_INTERVAL_ADDRESS.
Referenced by unittest().
getTempSeriesPointer()
double EEPROM_TC::getTempSeriesPointer ()
Definition at line 86 of file EEPROM_TC.cpp.
{
   return eepromReadDouble(TEMP_SERIES_POINTER_ADDRESS);
 }
References eepromReadDouble(), and TEMP_SERIES_POINTER_ADDRESS.
Referenced by unittest().
getTempSeriesSize()
double EEPROM_TC::getTempSeriesSize ()
Definition at line 83 of file EEPROM_TC.cpp.
{
   return eepromReadDouble(TEMP_SERIES_SIZE_ADDRESS);
 }
References eepromReadDouble(), and TEMP_SERIES_SIZE_ADDRESS.
Referenced by unittest().
instance()
EEPROM_TC * EEPROM_TC::instance () static
accessor for singleton
Definition at line 10 of file EEPROM_TC.cpp.
{
   if (!_instance) {
     _instance = new EEPROM_TC();
   }
   return _instance;
 }
References _instance, and EEPROM_TC().
Referenced by SetTempSetPoint::setValue(), and unittest().
setAmplitude()
void EEPROM_TC::setAmplitude (double value)
Definition at line 130 of file EEPROM_TC.cpp.
{
   eepromWriteDouble(AMPLITUDE_ADDRESS, value);
 }
References AMPLITUDE_ADDRESS, eepromWriteDouble(), and value.
Referenced by unittest().
setCorrectedTemp()
void EEPROM_TC::setCorrectedTemp (double value)
Definition at line 112 of file EEPROM_TC.cpp.
{
   eepromWriteDouble(TEMP_CORR_ADDRESS, value);
 }
References eepromWriteDouble(), TEMP_CORR_ADDRESS, and value.
Referenced by unittest().
setFrequency()
void EEPROM_TC::setFrequency (double value)
Definition at line 133 of file EEPROM_TC.cpp.
{
   eepromWriteDouble(FREQUENCY_ADDRESS, value);
 }
References eepromWriteDouble(), FREQUENCY_ADDRESS, and value.
Referenced by unittest().
setGranularity()
void EEPROM_TC::setGranularity (double value)
Definition at line 136 of file EEPROM_TC.cpp.
{
   eepromWriteDouble(GRANULARITY_ADDRESS, value);
 }
References eepromWriteDouble(), GRANULARITY_ADDRESS, and value.
Referenced by unittest().
setHeat()
void EEPROM_TC::setHeat (double value)
Definition at line 127 of file EEPROM_TC.cpp.
{
   eepromWriteDouble(HEAT_ADDRESS, value);
 }
References eepromWriteDouble(), HEAT_ADDRESS, and value.
Referenced by unittest().
setKD()
void EEPROM_TC::setKD (double value)
Definition at line 121 of file EEPROM_TC.cpp.
{
   eepromWriteDouble(KD_ADDRESS, value);
 }
References eepromWriteDouble(), KD_ADDRESS, and value.
Referenced by unittest().
setKI()
void EEPROM_TC::setKI (double value)
Definition at line 118 of file EEPROM_TC.cpp.
{
   eepromWriteDouble(KI_ADDRESS, value);
 }
References eepromWriteDouble(), KI_ADDRESS, and value.
Referenced by unittest().
setKP()
void EEPROM_TC::setKP (double value)
Definition at line 115 of file EEPROM_TC.cpp.
{
   eepromWriteDouble(KP_ADDRESS, value);
 }
References eepromWriteDouble(), KP_ADDRESS, and value.
Referenced by unittest().
setMac()
void EEPROM_TC::setMac (double value)
Definition at line 124 of file EEPROM_TC.cpp.
{
   eepromWriteDouble(MAC_ADDRESS, value);
 }
References eepromWriteDouble(), MAC_ADDRESS, and value.
Referenced by unittest().
setMaxDataAge()
void EEPROM_TC::setMaxDataAge (double value)
Definition at line 139 of file EEPROM_TC.cpp.
{
   eepromWriteDouble(MAX_DATA_AGE_ADDRESS, value);
 }
References eepromWriteDouble(), MAX_DATA_AGE_ADDRESS, and value.
Referenced by unittest().
setPH()
void EEPROM_TC::setPH (double value)
Definition at line 103 of file EEPROM_TC.cpp.
{
   eepromWriteDouble(PH_ADDRESS, value);
 }
References eepromWriteDouble(), PH_ADDRESS, and value.
Referenced by unittest().
setPHDelay()
void EEPROM_TC::setPHDelay (double value)
Definition at line 157 of file EEPROM_TC.cpp.
{
   eepromWriteDouble(PH_DELAY_ADDRESS, value);
 }
References eepromWriteDouble(), PH_DELAY_ADDRESS, and value.
Referenced by unittest().
setPHInterval()
void EEPROM_TC::setPHInterval (double value)
Definition at line 154 of file EEPROM_TC.cpp.
{
   eepromWriteDouble(PH_INTERVAL_ADDRESS, value);
 }
References eepromWriteDouble(), PH_INTERVAL_ADDRESS, and value.
Referenced by unittest().
setPHSeriesPointer()
void EEPROM_TC::setPHSeriesPointer (double value)
Definition at line 145 of file EEPROM_TC.cpp.
{
   eepromWriteDouble(PH_SERIES_POINTER_ADDRESS, value);
 }
References eepromWriteDouble(), PH_SERIES_POINTER_ADDRESS, and value.
Referenced by unittest().
setPHSeriesSize()
void EEPROM_TC::setPHSeriesSize (double value)
Definition at line 142 of file EEPROM_TC.cpp.
{
   eepromWriteDouble(PH_SERIES_SIZE_ADDRESS, value);
 }
References eepromWriteDouble(), PH_SERIES_SIZE_ADDRESS, and value.
Referenced by unittest().
setTankID()
void EEPROM_TC::setTankID (double value)
Definition at line 109 of file EEPROM_TC.cpp.
{
   eepromWriteDouble(TANK_ID_ADDRESS, value);
 }
References eepromWriteDouble(), TANK_ID_ADDRESS, and value.
Referenced by unittest().
setTemp()
void EEPROM_TC::setTemp (double value)
Definition at line 106 of file EEPROM_TC.cpp.
{
   eepromWriteDouble(TEMP_ADDRESS, value);
 }
References eepromWriteDouble(), TEMP_ADDRESS, and value.
Referenced by SetTempSetPoint::setValue(), and unittest().
setTempDelay()
void EEPROM_TC::setTempDelay (double value)
Definition at line 163 of file EEPROM_TC.cpp.
{
   eepromWriteDouble(TEMP_DELAY_ADDRESS, value);
 }
References eepromWriteDouble(), TEMP_DELAY_ADDRESS, and value.
Referenced by unittest().
setTempInterval()
void EEPROM_TC::setTempInterval (double value)
Definition at line 160 of file EEPROM_TC.cpp.
{
   eepromWriteDouble(TEMP_INTERVAL_ADDRESS, value);
 }
References eepromWriteDouble(), TEMP_INTERVAL_ADDRESS, and value.
Referenced by unittest().
setTempSeriesPointer()
void EEPROM_TC::setTempSeriesPointer (double value)
Definition at line 151 of file EEPROM_TC.cpp.
{
   eepromWriteDouble(TEMP_SERIES_POINTER_ADDRESS, value);
 }
References eepromWriteDouble(), TEMP_SERIES_POINTER_ADDRESS, and value.
Referenced by unittest().
setTempSeriesSize()
void EEPROM_TC::setTempSeriesSize (double value)
Definition at line 148 of file EEPROM_TC.cpp.
{
   eepromWriteDouble(TEMP_SERIES_SIZE_ADDRESS, value);
 }
References eepromWriteDouble(), TEMP_SERIES_SIZE_ADDRESS, and value.
Referenced by unittest().
Member Data Documentation
_instance
EEPROM_TC * EEPROM_TC::_instance = nullptr static private
Definition at line 63 of file EEPROM_TC.h.
Referenced by instance().
AMPLITUDE_ADDRESS
const int EEPROM_TC::AMPLITUDE_ADDRESS = 56 private
Definition at line 75 of file EEPROM_TC.h.
Referenced by getAmplitude(), and setAmplitude().
FREQUENCY_ADDRESS
const int EEPROM_TC::FREQUENCY_ADDRESS = 60 private
Definition at line 76 of file EEPROM_TC.h.
Referenced by getFrequency(), and setFrequency().
GRANULARITY_ADDRESS
const int EEPROM_TC::GRANULARITY_ADDRESS = 64 private
Definition at line 77 of file EEPROM_TC.h.
Referenced by getGranularity(), and setGranularity().
HEAT_ADDRESS
const int EEPROM_TC::HEAT_ADDRESS = 52 private
Definition at line 74 of file EEPROM_TC.h.
Referenced by getHeat(), and setHeat().
KD_ADDRESS
const int EEPROM_TC::KD_ADDRESS = 36 private
Definition at line 72 of file EEPROM_TC.h.
Referenced by getKD(), and setKD().
KI_ADDRESS
const int EEPROM_TC::KI_ADDRESS = 28 private
Definition at line 71 of file EEPROM_TC.h.
Referenced by getKI(), and setKI().
KP_ADDRESS
const int EEPROM_TC::KP_ADDRESS = 20 private
Definition at line 70 of file EEPROM_TC.h.
Referenced by getKP(), and setKP().
MAC_ADDRESS
const int EEPROM_TC::MAC_ADDRESS = 44 private
Definition at line 73 of file EEPROM_TC.h.
Referenced by getMac(), and setMac().
MAX_DATA_AGE_ADDRESS
const int EEPROM_TC::MAX_DATA_AGE_ADDRESS = 68 private
Definition at line 78 of file EEPROM_TC.h.
Referenced by getMaxDataAge(), and setMaxDataAge().
PH_ADDRESS
const int EEPROM_TC::PH_ADDRESS = 0 private
Definition at line 66 of file EEPROM_TC.h.
Referenced by getPH(), and setPH().
PH_DELAY_ADDRESS
const int EEPROM_TC::PH_DELAY_ADDRESS = 92 private
Definition at line 84 of file EEPROM_TC.h.
Referenced by getPHDelay(), and setPHDelay().
PH_INTERVAL_ADDRESS
const int EEPROM_TC::PH_INTERVAL_ADDRESS = 88 private
Definition at line 83 of file EEPROM_TC.h.
Referenced by getPHInterval(), and setPHInterval().
PH_SERIES_POINTER_ADDRESS
const int EEPROM_TC::PH_SERIES_POINTER_ADDRESS = 76 private
Definition at line 80 of file EEPROM_TC.h.
Referenced by getPHSeriesPointer(), and setPHSeriesPointer().
PH_SERIES_SIZE_ADDRESS
const int EEPROM_TC::PH_SERIES_SIZE_ADDRESS = 72 private
Definition at line 79 of file EEPROM_TC.h.
Referenced by getPHSeriesSize(), and setPHSeriesSize().
TANK_ID_ADDRESS
const int EEPROM_TC::TANK_ID_ADDRESS = 8 private
Definition at line 68 of file EEPROM_TC.h.
Referenced by getTankID(), and setTankID().
TEMP_ADDRESS
const int EEPROM_TC::TEMP_ADDRESS = 4 private
Definition at line 67 of file EEPROM_TC.h.
Referenced by getTemp(), and setTemp().
TEMP_CORR_ADDRESS
const int EEPROM_TC::TEMP_CORR_ADDRESS = 12 private
Definition at line 69 of file EEPROM_TC.h.
Referenced by getCorrectedTemp(), and setCorrectedTemp().
TEMP_DELAY_ADDRESS
const int EEPROM_TC::TEMP_DELAY_ADDRESS = 100 private
Definition at line 86 of file EEPROM_TC.h.
Referenced by getTempDelay(), and setTempDelay().
TEMP_INTERVAL_ADDRESS
const int EEPROM_TC::TEMP_INTERVAL_ADDRESS = 96 private
Definition at line 85 of file EEPROM_TC.h.
Referenced by getTempInterval(), and setTempInterval().
TEMP_SERIES_POINTER_ADDRESS
const int EEPROM_TC::TEMP_SERIES_POINTER_ADDRESS = 84 private
Definition at line 82 of file EEPROM_TC.h.
Referenced by getTempSeriesPointer(), and setTempSeriesPointer().
TEMP_SERIES_SIZE_ADDRESS
const int EEPROM_TC::TEMP_SERIES_SIZE_ADDRESS = 80 private
Definition at line 81 of file EEPROM_TC.h.
Referenced by getTempSeriesSize(), and setTempSeriesSize().
The documentation for this class was generated from the following files:
src/Devices/EEPROM_TC.h
src/Devices/EEPROM_TC.cpp