Tank Controller Lib: UIState Class Reference
UIState Class Reference abstract
#include <UIState.h>
Public Member Functions
UIState ()
virtual ~UIState ()
virtual void handleKey (char key)=0
virtual const char * prompt ()=0
Protected Member Functions
void changeState (UIState *state)
Detailed Description
Abstract superclass for the TankController UI states Concrete subclass for the initial (start) state
Definition at line 10 of file UIState.h.
Constructor & Destructor Documentation
UIState()
UIState::UIState () inline
Definition at line 12 of file UIState.h.
             {
   }
~UIState()
virtual UIState::~UIState () inline virtual
Definition at line 14 of file UIState.h.
                      {
   }
Member Function Documentation
changeState()
void UIState::changeState (UIState * state) inline protected
Definition at line 20 of file UIState.h.
{
     TankControllerLib::instance()->changeState(state);
   }
References TankControllerLib::changeState(), TankControllerLib::instance(), and state.
Referenced by MainMenu::handleKey(), NumCollectorState::handleKey(), SetPHSetPoint::handleKey(), and SetTempSetPoint::setValue().
handleKey()
virtual void UIState::handleKey (char key) pure virtual
Implemented in TemperatureCalibration, SetPHSetPoint, SetChillOrHeat, SeeTankID, SeePIDConstants, SeeDeviceUptime, ResetLCDScreen, PIDTuningMenu, PHCalibration, NumCollectorState, ManualSetTime, MainMenu, EnablePID, ChangeTankID, ChangeGoogleSheetInterval, and CalibrationManagement.
Referenced by TankControllerLib::loop().
prompt()
virtual const char* UIState::prompt () pure virtual
Implemented in TemperatureCalibration, SetTempSetPoint, SetPHSetPoint, SetChillOrHeat, SeeTankID, SeePIDConstants, SeeDeviceUptime, ResetLCDScreen, PIDTuningMenu, PHCalibration, ManualSetTime, MainMenu, EnablePID, ChangeTankID, ChangeGoogleSheetInterval, and CalibrationManagement.
Referenced by TankControllerLib::loop().
The documentation for this class was generated from the following file:
src/UIState/UIState.h