Tank Controller Lib: Serial_TC Class Reference
Serial_TC Class Reference
#include <Serial_TC.h>
Public Member Functions
void print (char aChar)
void print (uint16_t anInt)
void print (String aString)
void print (String aString, char aChar)
void print (String aString, int anInt)
void print (String aString, int anInt, int format)
void print (String aString, String aString2)
void println ()
void print_mac (byte mac[])
void print_PID (double Kp, double Ki, double Kd, double output)
void print_two_digits (int value)
void write (byte aByte)
void write (char arr[], int anInt)
Static Public Member Functions
static Serial_TC * instance ()
Private Member Functions
Serial_TC ()
Static Private Attributes
static Serial_TC * _instance = nullptr
Detailed Description
This class is for the Serial Commands used in Tank Controller. Serial here mostly deals with writing or printing data over through the serial port. Serial.print and Serial.write can be called in different ways to print data. Also print_PID, print_DataTime, print_mac are used to print the PID information, current date information, and the mac address.
Definition at line 12 of file Serial_TC.h.
Constructor & Destructor Documentation
Serial_TC()
Serial_TC::Serial_TC () private
constructor (private so clients use the singleton)
Definition at line 24 of file Serial_TC.cpp.
                      {
   Serial.begin(9600);
 }
Referenced by instance().
Member Function Documentation
instance()
Serial_TC * Serial_TC::instance () static
static member function to return singleton
Definition at line 13 of file Serial_TC.cpp.
{
   if (!_instance) {
     _instance = new Serial_TC();
   }
   return _instance;
 }
References _instance, and Serial_TC().
Referenced by DateTime_TC::printToSerial(), TankControllerLib::TankControllerLib(), and unittest().
print() [1/7]
void Serial_TC::print (char aChar)
Definition at line 28 of file Serial_TC.cpp.
{
   Serial.print(aChar);
 }
Referenced by TankControllerLib::loop(), DateTime_TC::printToSerial(), TankControllerLib::setup(), TankControllerLib::TankControllerLib(), unittest(), and TankControllerLib::version().
print() [2/7]
void Serial_TC::print (String aString)
Definition at line 36 of file Serial_TC.cpp.
{
   Serial.println(aString);
 }
print() [3/7]
void Serial_TC::print (String aString, char aChar)
Definition at line 40 of file Serial_TC.cpp.
{
   Serial.print(aString);
   Serial.println(aChar);
 }
print() [4/7]
void Serial_TC::print (String aString, int anInt)
Definition at line 45 of file Serial_TC.cpp.
{
   Serial.print(aString);
   Serial.println(anInt);
 }
print() [5/7]
void Serial_TC::print (String aString, int anInt, int format)
Definition at line 50 of file Serial_TC.cpp.
{
   Serial.print(aString);
   Serial.println(anInt, format);
 }
print() [6/7]
void Serial_TC::print (String aString, String aString2)
Definition at line 55 of file Serial_TC.cpp.
{
   Serial.print(aString);
   Serial.println(aString2);
 }
print() [7/7]
void Serial_TC::print (uint16_t anInt)
Definition at line 32 of file Serial_TC.cpp.
{
   Serial.print(anInt);
 }
print_mac()
void Serial_TC::print_mac (byte mac[])
Definition at line 60 of file Serial_TC.cpp.
{
   Serial.print(F("MAC Address: "));
   Serial.print(mac[0]);
   for (int i = 1; i < 6; ++i) {
     Serial.print(':');
     Serial.print(mac[i]);
   }
   Serial.println();
 }
Referenced by unittest().
print_PID()
void Serial_TC::print_PID (double Kp, double Ki, double Kd, double output)
Print the PID constants and output
Definition at line 73 of file Serial_TC.cpp.
{
   Serial.print(F("Kp:"));
   Serial.print(Kp);
   Serial.print(F(" Ki:"));
   Serial.print(Ki);
   Serial.print(F(" Kd:"));
   Serial.println(Kd);
   Serial.print(F("PID output (s): "));
   Serial.println(output / 1000, 1);
 }
Referenced by unittest().
print_two_digits()
void Serial_TC::print_two_digits (int value)
function to add a leading zero digit
Definition at line 87 of file Serial_TC.cpp.
{
   if (value < 10) {
     Serial.print('0');
   }
   Serial.print(value, DEC);
 }
References value.
Referenced by DateTime_TC::printToSerial(), and unittest().
println()
void Serial_TC::println () inline
Definition at line 25 of file Serial_TC.h.
                  {
     Serial.println();
   }
Referenced by DateTime_TC::printToSerial(), and unittest().
write() [1/2]
void Serial_TC::write (byte aByte)
Definition at line 94 of file Serial_TC.cpp.
{
   Serial.write(aByte);
 }
Referenced by unittest().
write() [2/2]
void Serial_TC::write (char arr[], int anInt)
Definition at line 98 of file Serial_TC.cpp.
{
   Serial.write(arr, anInt);
 }
Member Data Documentation
_instance
Serial_TC * Serial_TC::_instance = nullptr static private
static variable for singleton
Definition at line 36 of file Serial_TC.h.
Referenced by instance().
The documentation for this class was generated from the following files:
src/Devices/Serial_TC.h
src/Devices/Serial_TC.cpp