Tank Controller Lib: TemperatureControl Class Reference
TemperatureControl Class Reference abstract
#include <TemperatureControl.h>
Public Member Functions
TemperatureControl ()
void setTargetTemperature (double newTemperature)
virtual void updateControl (double currentTemperature)=0
bool getCurrentSwitchState ()
Protected Member Functions
void turnOn (bool state)
Protected Attributes
const int PIN = 47
const double DELTA = 0.05
double targetTemperature
bool currentSwitchState = false
Detailed Description
Temperature Control Controlling the tank temperature is done by external devices that are controlled by setting designated pins on the Arduino.
Definition at line 9 of file TemperatureControl.h.
Constructor & Destructor Documentation
TemperatureControl()
TemperatureControl::TemperatureControl () inline
Definition at line 19 of file TemperatureControl.h.
{
   }
Member Function Documentation
getCurrentSwitchState()
bool TemperatureControl::getCurrentSwitchState () inline
Definition at line 25 of file TemperatureControl.h.
{
     return currentSwitchState;
   }
References currentSwitchState.
Referenced by unittest().
setTargetTemperature()
void TemperatureControl::setTargetTemperature (double newTemperature) inline
Definition at line 21 of file TemperatureControl.h.
{
     targetTemperature = newTemperature;
   }
References targetTemperature.
Referenced by unittest().
turnOn()
void TemperatureControl::turnOn (bool state) protected
Definition at line 3 of file TemperatureControl.cpp.
{
   digitalWrite(PIN, newState ? LOW : HIGH);
   currentSwitchState = newState;
 }
References currentSwitchState, and PIN.
Referenced by Heater::updateControl(), and Chiller::updateControl().
updateControl()
virtual void TemperatureControl::updateControl (double currentTemperature) pure virtual
Implemented in Chiller, and Heater.
Member Data Documentation
currentSwitchState
bool TemperatureControl::currentSwitchState = false protected
Definition at line 14 of file TemperatureControl.h.
Referenced by getCurrentSwitchState(), and turnOn().
DELTA
const double TemperatureControl::DELTA = 0.05 protected
Definition at line 12 of file TemperatureControl.h.
Referenced by Heater::updateControl(), and Chiller::updateControl().
PIN
const int TemperatureControl::PIN = 47 protected
Definition at line 11 of file TemperatureControl.h.
Referenced by turnOn().
targetTemperature
double TemperatureControl::targetTemperature protected
Definition at line 13 of file TemperatureControl.h.
Referenced by setTargetTemperature(), Heater::updateControl(), and Chiller::updateControl().
The documentation for this class was generated from the following files:
src/Devices/TemperatureControl.h
src/Devices/TemperatureControl.cpp