Tank Controller Lib: DateTime_TC Class Reference
DateTime_TC Class Reference
#include <DateTime_TC.h>
Public Member Functions
DateTime_TC (uint16_t year, uint8_t month, uint8_t day, uint8_t hour=0, uint8_t min=0, uint8_t sec=0)
void printToSerial ()
void yearMonthAsPath (char *buffer, size_t size)
Static Public Member Functions
static DateTime_TC now ()
Detailed Description
Definition at line 9 of file DateTime_TC.h.
Constructor & Destructor Documentation
DateTime_TC()
DateTime_TC::DateTime_TC (uint16_t year, uint8_t month, uint8_t day, uint8_t hour = 0, uint8_t min = 0, uint8_t sec = 0)
Constructor
Definition at line 15 of file DateTime_TC.cpp.
     : DateTime(year, month, day, hour, min, sec) {
 }
Referenced by now().
Member Function Documentation
now()
DateTime_TC DateTime_TC::now () static
Definition at line 6 of file DateTime_TC.cpp.
{
   DateTime now = RTC_PCF8523::now();
   return DateTime_TC(now.year(), now.month(), now.day(), now.hour(), now.minute(), now.second());
 }
References DateTime_TC().
Referenced by unittest().
printToSerial()
void DateTime_TC::printToSerial ()
output dateTime to serialPort(DigitalClockDisplay.ino) "2020-11-26 18:55:15"
Definition at line 23 of file DateTime_TC.cpp.
{
   Serial_TC* serial = Serial_TC::instance();
   serial->print(year());
   serial->print('-');
   serial->print_two_digits(month());
   serial->print('-');
   serial->print_two_digits(day());
   serial->print(' ');
   serial->print_two_digits(hour());
   serial->print(':');
   serial->print_two_digits(minute());
   serial->print(':');
   serial->print_two_digits(second());
   serial->println();
 }
References Serial_TC::instance(), Serial_TC::print(), Serial_TC::print_two_digits(), and Serial_TC::println().
Referenced by unittest().
yearMonthAsPath()
void DateTime_TC::yearMonthAsPath (char * buffer, size_t sizeOfBuffer)
populate a buffer with dateTime as a path: "/2020/09"
Definition at line 42 of file DateTime_TC.cpp.
{
   memset(buffer, 0, sizeOfBuffer);
   if (sizeOfBuffer < 9) {  // is there enough room?
     return;
   }
   buffer[0] = '/';
   itoa(year(), buffer + 1, 10);
   buffer[5] = '/';
   int i = 6;
   if (month() < 10) {
     buffer[i++] = '0';
   }
   itoa(month(), buffer + i, 10);
 }
Referenced by unittest().
The documentation for this class was generated from the following files:
src/Devices/DateTime_TC.h
src/Devices/DateTime_TC.cpp