Tank Controller Lib: Keypad_TC Class Reference
Keypad_TC Class Reference
#include <Keypad_TC.h>
Public Member Functions
char waitForKey ()
char getKey ()
Static Public Member Functions
static Keypad_TC * instance ()
static Keypad * _getPuppet ()
Private Member Functions
Keypad_TC ()
Private Attributes
char lastKey
Static Private Attributes
static Keypad_TC * _instance = nullptr
static Keypad puppetPad = Keypad(makeKeymap(STD_KEYS), ROW_PINS, COL_PINS, 4, 4)
Detailed Description
Definition at line 10 of file Keypad_TC.h.
Constructor & Destructor Documentation
Keypad_TC()
Keypad_TC::Keypad_TC () private
Definition at line 13 of file Keypad_TC.cpp.
                      {
 }
Referenced by instance().
Member Function Documentation
_getPuppet()
static Keypad* Keypad_TC::_getPuppet () inline static
Definition at line 20 of file Keypad_TC.h.
{
     return &puppetPad;
   }
References puppetPad.
Referenced by key(), and unittest().
getKey()
char Keypad_TC::getKey ()
Get a key from the keypad if one is queued for use
Definition at line 38 of file Keypad_TC.cpp.
{
   lastKey = puppetPad.getKey();
   return lastKey;
 }
References lastKey, and puppetPad.
Referenced by TankControllerLib::loop(), and unittest().
instance()
Keypad_TC * Keypad_TC::instance () static
accessor for singleton
Definition at line 20 of file Keypad_TC.cpp.
{
   if (!_instance) {
     _instance = new Keypad_TC();
   }
   return _instance;
 }
References _instance, and Keypad_TC().
Referenced by key(), TankControllerLib::loop(), and unittest().
waitForKey()
char Keypad_TC::waitForKey ()
Gets a key from the keypad by blocking on key press
Definition at line 30 of file Keypad_TC.cpp.
{
   lastKey = puppetPad.waitForKey();
   return lastKey;
 }
References lastKey, and puppetPad.
Referenced by unittest().
Member Data Documentation
_instance
Keypad_TC * Keypad_TC::_instance = nullptr static private
Definition at line 26 of file Keypad_TC.h.
Referenced by instance().
lastKey
char Keypad_TC::lastKey private
Definition at line 31 of file Keypad_TC.h.
Referenced by getKey(), and waitForKey().
puppetPad
Keypad Keypad_TC::puppetPad = Keypad(makeKeymap(STD_KEYS), ROW_PINS, COL_PINS, 4, 4) static private
Definition at line 27 of file Keypad_TC.h.
Referenced by _getPuppet(), getKey(), and waitForKey().
The documentation for this class was generated from the following files:
src/Devices/Keypad_TC.h
src/Devices/Keypad_TC.cpp