Tank Controller Lib: EthernetServer_TC Class Reference
EthernetServer_TC Class Reference
#include <EthernetServer_TC.h>
Public Member Functions
void handleRequest ()
virtual String className () const
Static Public Member Functions
static EthernetServer_TC * instance ()
Private Member Functions
EthernetServer_TC (uint16_t port)
Static Private Attributes
static EthernetServer_TC * _instance = nullptr
Detailed Description
EthernetServer_TC provides wrapper for web server for TankController
If running in test mode, superclass = EthernetServer_CI
Definition at line 15 of file EthernetServer_TC.h.
Constructor & Destructor Documentation
EthernetServer_TC()
EthernetServer_TC::EthernetServer_TC (uint16_t port) private
Constructor: which port should we listen on?
Definition at line 21 of file EthernetServer_TC.cpp.
                                                   : EthernetServer(port) {
   begin();
   Serial.print(F("Ethernet Server is listening on port 80 of ??????"));
   //   TODO: Need Mock board for .localIP to work
   //   Serial.println(Ethernet.localIP());
 }
Referenced by instance().
Member Function Documentation
className()
virtual String EthernetServer_TC::className () const inline virtual
Definition at line 21 of file EthernetServer_TC.h.
{
     return "EthernetServer_TC";
   }
Referenced by unittest().
handleRequest()
void EthernetServer_TC::handleRequest ()
Look for request from external client and handle it. This (incomplete) code copied from HandleRequest()
Definition at line 32 of file EthernetServer_TC.cpp.
{
   // listen for incoming clients
   EthernetClient rpc_client = available();  // Raspberry Pi Client
   if (rpc_client) {
     // TODO: NEED TO IMPLEMENT
     // HandleRequest(rpc_client);
     // give the web browser time to receive the data
     // delay(ONE_SECOND_DELAY_IN_MILLIS);
     // close the connection:
     rpc_client.stop();
     Serial.println(F("rpc_client disconnected"));
   }
 }
instance()
EthernetServer_TC * EthernetServer_TC::instance () static
accessor for singleton
Definition at line 10 of file EthernetServer_TC.cpp.
{
   if (!_instance) {
     _instance = new EthernetServer_TC(80);
   }
   return _instance;
 }
References _instance, and EthernetServer_TC().
Referenced by unittest().
Member Data Documentation
_instance
EthernetServer_TC * EthernetServer_TC::_instance = nullptr static private
Definition at line 27 of file EthernetServer_TC.h.
Referenced by instance().
The documentation for this class was generated from the following files:
src/Devices/EthernetServer_TC.h
src/Devices/EthernetServer_TC.cpp