Tank Controller Lib: test/EEPROM.cpp File Reference
EEPROM.cpp File Reference
#include <Arduino.h>
#include <ArduinoUnitTests.h>
#include "EEPROM_TC.h"
Functions
unittest (Main)
unittest (eeprom_Read_and_Write_Double)
unittest (PH)
unittest (Temp)
unittest (TankID)
unittest (CorrectedTemp)
unittest (KP)
unittest (KI)
unittest (KD)
unittest (Mac)
unittest (Heat)
unittest (Amplitude)
unittest (Frequency)
unittest (Granularity)
unittest (MaxDataAge)
unittest (PHSeriesSize)
unittest (PHSeriesPointer)
unittest (TempSeriesSize)
unittest (TempSeriesPointer)
unittest (PHInterval)
unittest (PHDelay)
unittest (TempInterval)
unittest (TempDelay)
Function Documentation
unittest() [1/23]
unittest (Amplitude)
Definition at line 93 of file EEPROM.cpp.
                     {
   EEPROM_TC* singleton = EEPROM_TC::instance();
   assertNAN(singleton->getAmplitude());
   singleton->setAmplitude(12);
   assertEqual(12, singleton->getAmplitude());
 }
References EEPROM_TC::getAmplitude(), EEPROM_TC::instance(), and EEPROM_TC::setAmplitude().
unittest() [2/23]
unittest (CorrectedTemp)
Definition at line 51 of file EEPROM.cpp.
{
   EEPROM_TC* singleton = EEPROM_TC::instance();
   assertNAN(singleton->getCorrectedTemp());
   singleton->setCorrectedTemp(6);
   assertEqual(6, singleton->getCorrectedTemp());
 }
References EEPROM_TC::getCorrectedTemp(), EEPROM_TC::instance(), and EEPROM_TC::setCorrectedTemp().
unittest() [3/23]
unittest (eeprom_Read_and_Write_Double)
Definition at line 17 of file EEPROM.cpp.
{
   EEPROM_TC* test = EEPROM_TC::instance();
   const int TEST_ADDRESS = 110;  // a couple addresses beyond stored data
   // integer
   test->eepromWriteDouble(TEST_ADDRESS, 10);
   assertEqual(10, test->eepromReadDouble(TEST_ADDRESS));
   // double
   test->eepromWriteDouble(TEST_ADDRESS, 12.23);
   assertEqual(12.23, test->eepromReadDouble(TEST_ADDRESS));
 }
References EEPROM_TC::instance().
unittest() [4/23]
unittest (Frequency)
Definition at line 100 of file EEPROM.cpp.
                     {
   EEPROM_TC* singleton = EEPROM_TC::instance();
   assertNAN(singleton->getFrequency());
   singleton->setFrequency(13);
   assertEqual(13, singleton->getFrequency());
 }
References EEPROM_TC::getFrequency(), EEPROM_TC::instance(), and EEPROM_TC::setFrequency().
unittest() [5/23]
unittest (Granularity)
Definition at line 107 of file EEPROM.cpp.
                       {
   EEPROM_TC* singleton = EEPROM_TC::instance();
   assertNAN(singleton->getGranularity());
   singleton->setGranularity(14);
   assertEqual(14, singleton->getGranularity());
 }
References EEPROM_TC::getGranularity(), EEPROM_TC::instance(), and EEPROM_TC::setGranularity().
unittest() [6/23]
unittest (Heat)
Definition at line 86 of file EEPROM.cpp.
                {
   EEPROM_TC* singleton = EEPROM_TC::instance();
   assertNAN(singleton->getHeat());
   singleton->setHeat(11);
   assertEqual(11, singleton->getHeat());
 }
References EEPROM_TC::getHeat(), EEPROM_TC::instance(), and EEPROM_TC::setHeat().
unittest() [7/23]
unittest (KD)
Definition at line 72 of file EEPROM.cpp.
              {
   EEPROM_TC* singleton = EEPROM_TC::instance();
   assertNAN(singleton->getKD());
   singleton->setKD(9);
   assertEqual(9, singleton->getKD());
 }
References EEPROM_TC::getKD(), EEPROM_TC::instance(), and EEPROM_TC::setKD().
unittest() [8/23]
unittest (KI)
Definition at line 65 of file EEPROM.cpp.
              {
   EEPROM_TC* singleton = EEPROM_TC::instance();
   assertNAN(singleton->getKI());
   singleton->setKI(8);
   assertEqual(8, singleton->getKI());
 }
References EEPROM_TC::getKI(), EEPROM_TC::instance(), and EEPROM_TC::setKI().
unittest() [9/23]
unittest (KP)
Definition at line 58 of file EEPROM.cpp.
              {
   EEPROM_TC* singleton = EEPROM_TC::instance();
   assertNAN(singleton->getKP());
   singleton->setKP(7);
   assertEqual(7, singleton->getKP());
 }
References EEPROM_TC::getKP(), EEPROM_TC::instance(), and EEPROM_TC::setKP().
unittest() [10/23]
unittest (Mac)
Definition at line 79 of file EEPROM.cpp.
               {
   EEPROM_TC* singleton = EEPROM_TC::instance();
   assertNAN(singleton->getMac());
   singleton->setMac(10);
   assertEqual(10, singleton->getMac());
 }
References EEPROM_TC::getMac(), EEPROM_TC::instance(), and EEPROM_TC::setMac().
unittest() [11/23]
unittest (Main)
Definition at line 6 of file EEPROM.cpp.
                {
   // Test singleton
   EEPROM_TC* singleton1 = nullptr;
   singleton1 = EEPROM_TC::instance();
   assertNotNull(singleton1);
   EEPROM_TC* singleton2 = nullptr;
   singleton2 = EEPROM_TC::instance();
   assertNotNull(singleton2);
   assertEqual(singleton1, singleton2);
 }
References EEPROM_TC::instance().
unittest() [12/23]
unittest (MaxDataAge)
Definition at line 114 of file EEPROM.cpp.
                      {
   EEPROM_TC* singleton = EEPROM_TC::instance();
   assertNAN(singleton->getMaxDataAge());
   singleton->setMaxDataAge(15);
   assertEqual(15, singleton->getMaxDataAge());
 }
References EEPROM_TC::getMaxDataAge(), EEPROM_TC::instance(), and EEPROM_TC::setMaxDataAge().
unittest() [13/23]
unittest (PH)
Definition at line 30 of file EEPROM.cpp.
              {
   EEPROM_TC* singleton = EEPROM_TC::instance();
   assertNAN(singleton->getPH());
   singleton->setPH(3.05);
   assertEqual(3.05, singleton->getPH());
 }
References EEPROM_TC::getPH(), EEPROM_TC::instance(), and EEPROM_TC::setPH().
unittest() [14/23]
unittest (PHDelay)
Definition at line 156 of file EEPROM.cpp.
                   {
   EEPROM_TC* singleton = EEPROM_TC::instance();
   assertNAN(singleton->getPHDelay());
   singleton->setPHDelay(21);
   assertEqual(21, singleton->getPHDelay());
 }
References EEPROM_TC::getPHDelay(), EEPROM_TC::instance(), and EEPROM_TC::setPHDelay().
unittest() [15/23]
unittest (PHInterval)
Definition at line 149 of file EEPROM.cpp.
                      {
   EEPROM_TC* singleton = EEPROM_TC::instance();
   assertNAN(singleton->getPHInterval());
   singleton->setPHInterval(20);
   assertEqual(20, singleton->getPHInterval());
 }
References EEPROM_TC::getPHInterval(), EEPROM_TC::instance(), and EEPROM_TC::setPHInterval().
unittest() [16/23]
unittest (PHSeriesPointer)
Definition at line 128 of file EEPROM.cpp.
{
   EEPROM_TC* singleton = EEPROM_TC::instance();
   assertNAN(singleton->getPHSeriesPointer());
   singleton->setPHSeriesPointer(17);
   assertEqual(17, singleton->getPHSeriesPointer());
 }
References EEPROM_TC::getPHSeriesPointer(), EEPROM_TC::instance(), and EEPROM_TC::setPHSeriesPointer().
unittest() [17/23]
unittest (PHSeriesSize)
Definition at line 121 of file EEPROM.cpp.
{
   EEPROM_TC* singleton = EEPROM_TC::instance();
   assertNAN(singleton->getPHSeriesSize());
   singleton->setPHSeriesSize(16);
   assertEqual(16, singleton->getPHSeriesSize());
 }
References EEPROM_TC::getPHSeriesSize(), EEPROM_TC::instance(), and EEPROM_TC::setPHSeriesSize().
unittest() [18/23]
unittest (TankID)
Definition at line 44 of file EEPROM.cpp.
                  {
   EEPROM_TC* singleton = EEPROM_TC::instance();
   assertNAN(singleton->getTankID());
   singleton->setTankID(5);
   assertEqual(5, singleton->getTankID());
 }
References EEPROM_TC::getTankID(), EEPROM_TC::instance(), and EEPROM_TC::setTankID().
unittest() [19/23]
unittest (Temp)
Definition at line 37 of file EEPROM.cpp.
                {
   EEPROM_TC* singleton = EEPROM_TC::instance();
   assertNAN(singleton->getTemp());
   singleton->setTemp(4);
   assertEqual(4, singleton->getTemp());
 }
References EEPROM_TC::getTemp(), EEPROM_TC::instance(), and EEPROM_TC::setTemp().
unittest() [20/23]
unittest (TempDelay)
Definition at line 170 of file EEPROM.cpp.
                     {
   EEPROM_TC* singleton = EEPROM_TC::instance();
   assertNAN(singleton->getTempDelay());
   singleton->setTempDelay(23);
   assertEqual(23, singleton->getTempDelay());
 }
References EEPROM_TC::getTempDelay(), EEPROM_TC::instance(), and EEPROM_TC::setTempDelay().
unittest() [21/23]
unittest (TempInterval)
Definition at line 163 of file EEPROM.cpp.
{
   EEPROM_TC* singleton = EEPROM_TC::instance();
   assertNAN(singleton->getTempInterval());
   singleton->setTempInterval(22);
   assertEqual(22, singleton->getTempInterval());
 }
References EEPROM_TC::getTempInterval(), EEPROM_TC::instance(), and EEPROM_TC::setTempInterval().
unittest() [22/23]
unittest (TempSeriesPointer)
Definition at line 142 of file EEPROM.cpp.
{
   EEPROM_TC* singleton = EEPROM_TC::instance();
   assertNAN(singleton->getTempSeriesPointer());
   singleton->setTempSeriesPointer(19);
   assertEqual(19, singleton->getTempSeriesPointer());
 }
References EEPROM_TC::getTempSeriesPointer(), EEPROM_TC::instance(), and EEPROM_TC::setTempSeriesPointer().
unittest() [23/23]
unittest (TempSeriesSize)
Definition at line 135 of file EEPROM.cpp.
{
   EEPROM_TC* singleton = EEPROM_TC::instance();
   assertNAN(singleton->getTempSeriesSize());
   singleton->setTempSeriesSize(18);
   assertEqual(18, singleton->getTempSeriesSize());
 }
References EEPROM_TC::getTempSeriesSize(), EEPROM_TC::instance(), and EEPROM_TC::setTempSeriesSize().