Tank Controller Lib: test/Ethernet.cpp File Reference
Ethernet.cpp File Reference
#include <Arduino.h>
#include <ArduinoUnitTests.h>
#include "Ethernet_TC.h"
Functions
unittest (Main)
Function Documentation
unittest()
unittest (Main)
Definition at line 6 of file Ethernet.cpp.
                {
   // Test singleton
   Ethernet_TC* singleton1 = nullptr;
   singleton1 = Ethernet_TC::getInstance();
   assertNotNull(singleton1);
   Ethernet_TC* singleton2 = nullptr;
   singleton2 = Ethernet_TC::getInstance();
   assertNotNull(singleton2);
   assertEqual(singleton1, singleton2);
   // Test that the default IP was used as a fall back (Assuming that there is no DHCP server to talk to)
   IPAddress defaultIP(192, 168, 1, 2);
   assertTrue(singleton1->getIP() == defaultIP);
   // Test DHCP is being maintained
   singleton1->renewDHCPLease();
   singleton1->renewDHCPLease();
   singleton1->renewDHCPLease();
   assertEqual(singleton1->getNumAttemptedDHCPReleases(), 3);
 }
References Ethernet_TC::getInstance(), Ethernet_TC::getIP(), Ethernet_TC::getNumAttemptedDHCPReleases(), and Ethernet_TC::renewDHCPLease().