Tank Controller Lib: test/Keypad.cpp File Reference
Keypad.cpp File Reference
#include <Arduino.h>
#include <ArduinoUnitTests.h>
#include "TankControllerLib.h"
Functions
unittest (constructor)
unittest (getKey)
unittest (waitForKey)
Function Documentation
unittest() [1/3]
unittest (constructor)
Definition at line 6 of file Keypad.cpp.
                       {
   // Test singleton
   Keypad_TC* singleton1 = nullptr;
   singleton1 = Keypad_TC::instance();
   assertNotNull(singleton1);
   Keypad_TC* singleton2 = nullptr;
   singleton2 = Keypad_TC::instance();
   assertNotNull(singleton2);
   assertEqual(singleton1, singleton2);
 }
References Keypad_TC::instance().
unittest() [2/3]
unittest (getKey)
Definition at line 17 of file Keypad.cpp.
                  {
   Keypad_TC* testKeypad = Keypad_TC::instance();
   Keypad* puppet = testKeypad->_getPuppet();
   assertEqual(NO_KEY, testKeypad->getKey());
   puppet->push_back('Q');
   assertEqual('Q', testKeypad->getKey());
   assertEqual(NO_KEY, testKeypad->getKey());
 }
References Keypad_TC::_getPuppet(), Keypad_TC::getKey(), and Keypad_TC::instance().
unittest() [3/3]
unittest (waitForKey)
Definition at line 26 of file Keypad.cpp.
                      {
   Keypad_TC* testKeypad = Keypad_TC::instance();
   Keypad* puppet = testKeypad->_getPuppet();
   puppet->push_back('Q');
   assertEqual('Q', testKeypad->waitForKey());
 }
References Keypad_TC::_getPuppet(), Keypad_TC::instance(), and Keypad_TC::waitForKey().