Tank Controller Lib: test/Menu.cpp File Reference
Menu.cpp File Reference
#include <Arduino.h>
#include <ArduinoUnitTests.h>
#include "TankControllerLib.h"
Functions
unittest (test)
Function Documentation
unittest()
unittest (test)
Definition at line 6 of file Menu.cpp.
                {
   TankControllerLib* tc = TankControllerLib::instance();
   LiquidCrystal_TC* lc = LiquidCrystal_TC::instance();
   Keypad* keypad = Keypad_TC::instance()->_getPuppet();
   std::vector<std::string> lines;
   tc->loop();
   lines = lc->getLines();
   assertEqual(" ONTHANK LAB", lc->getLines().at(0).substr(4));
   keypad->push_back('A');
   tc->loop();  // recognize and apply the key entry
   assertEqual("Set pH Set Point", lc->getLines().at(0));
   keypad->push_back('D');  // Don't finish (cancel)
   tc->loop();              // recognize and apply the key entry
   lines = lc->getLines();
   assertEqual("Main Menu       ", lc->getLines().at(0));
 }
References Keypad_TC::_getPuppet(), Keypad_TC::instance(), LiquidCrystal_TC::instance(), TankControllerLib::instance(), and TankControllerLib::loop().