Tank Controller Lib: test/TempProbe_TC_Test.cpp File Reference
TempProbe_TC_Test.cpp File Reference
#include <TempProbe_TC.h>
#include "Arduino.h"
#include "ArduinoUnitTests.h"
Functions
unittest (TempProbe_Test)
Function Documentation
unittest()
unittest (TempProbe_Test)
Definition at line 6 of file TempProbe_TC_Test.cpp.
{
   // Instance
   TempProbe_TC* tempProbe = TempProbe_TC::instance();
   // Test getResistance()
   uint16_t testRTD = tempProbe->getResistance();
   assertEqual(0, testRTD);
   // Test getTemperature()
   float testTemp = tempProbe->getTemperature();
   assertEqual(-242, (int)testTemp);
   // Test readFault()
   uint8_t testFault = tempProbe->readFault();
   assertEqual(0, testFault);
   // Test clearFault()
   tempProbe->clearFault();
   testFault = tempProbe->readFault();
   assertEqual(0, testFault);
 }
References TempProbe_TC::clearFault(), TempProbe_TC::getResistance(), TempProbe_TC::getTemperature(), TempProbe_TC::instance(), and TempProbe_TC::readFault().