Tank Controller Lib: test/SetTempSetPoint.cpp File Reference
SetTempSetPoint.cpp File Reference
#include "SetTempSetPoint.h"
#include <Arduino.h>
#include <ArduinoUnitTests.h>
#include <iostream>
#include "EEPROM_TC.h"
#include "LiquidCrystal_TC.h"
#include "TankControllerLib.h"
Functions
unittest (test)
unittest (Number_Digits)
unittest (Next_State)
Function Documentation
unittest() [1/3]
unittest (Next_State)
Definition at line 25 of file SetTempSetPoint.cpp.
                      {
   TankControllerLib* tc = TankControllerLib::instance();
   LiquidCrystal_TC* lc = LiquidCrystal_TC::instance();
   Keypad* keypad = Keypad_TC::instance()->_getPuppet();
   keypad->push_back('B');
   tc->loop();
   assertEqual("Set Temperature ", lc->getLines().at(0));
   keypad->push_back('A');
   tc->loop();
   assertEqual("Main Menu       ", lc->getLines().at(0));
 }
References Keypad_TC::_getPuppet(), Keypad_TC::instance(), LiquidCrystal_TC::instance(), TankControllerLib::instance(), and TankControllerLib::loop().
unittest() [2/3]
unittest (Number_Digits)
Definition at line 20 of file SetTempSetPoint.cpp.
{
   SetTempSetPoint test;
   assertEqual(4, test.getExpectedDigits());
 }
unittest() [3/3]
unittest (test)
Definition at line 12 of file SetTempSetPoint.cpp.
                {
   SetTempSetPoint test;
   // setValue
   test.setValue(50.05);
   assertEqual(50.05, EEPROM_TC::instance()->getTemp());
 }
References EEPROM_TC::instance().